name: Create Nuget package

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      - uses: actions/checkout@master
      
      - name: Generate package
        run: dotnet pack --configuration Release
      
      - name: Install NuGet.exe
        uses: warrenbuckley/Setup-Nuget@v1
  
      - name: Add registry
        run: nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/ajupov/index.json -Username ajupov -Password ${{ secrets.NUGET_PASSWORD }}
  
      - name: Push package
        run: nuget push .\bin\Release\*.nupkg -Source "GPR" -SkipDuplicate
